conditional rendering has been done to make sure that the latest versi…
gchq/Bailo pull request #1021
Opened 2024-01-19 14:14 UTC by TT38665

…on does not show when viewing a release

2024-01-19 15:54 UTC, a3957273 requested changes
We also probably don't want to display this when _editing_ a model, because the release semver can't be created there either!

2024-01-19 16:18 UTC, TT38665 commented
> We also probably don't want to display this when _editing_ a model, because the release semver can't be created there either!

It's covered in the conditional rendering. The latest version does not show when you click on a release or when editing a model.

2024-01-22 14:54 UTC, ARADDCC012 commented
> We also probably don't want to display this when _editing_ a model, because the release semver can't be created there either!

Can confirm that when the form is in `editable` mode, the form is being used for View and Edit. If it's not in `editable` mode the form is being used for Create only. So by conditionally showing the latest version when not in `editable` mode, it'll only show on the create release page.

2024-02-06 00:17 UTC, a3957273 approved these changes

2024-02-06 00:18 UTC, merged