Feature/allow models to be exported as pdfs
gchq/Bailo pull request #1030
Opened 2024-01-24 12:13 UTC by ARADDCC012

2024-01-24 12:15 UTC, ARADDCC012 commented on backend/src/routes/v2/model/modelcard/getModelCardExport.ts
> +  file: FileInterface
I don't think this is right, but I've followed the logic already set out in `backend/src/routes/v2/model/file/getDownloadFile.ts` as they're both returning a file as a stream.

2024-01-24 14:33 UTC, ARADDCC002 commented
Can we make the model title and description text bigger on the first page?

2024-01-24 14:39 UTC, ARADDCC002 approved these changes

2024-01-29 11:09 UTC, a3957273 requested changes

2024-02-05 16:54 UTC, closed without merging