disabled the releases and access requests tab on model page if no sch…
gchq/Bailo pull request #1033
Opened 2024-01-24 17:04 UTC by ARADDCC002

…ema selected

2024-01-26 14:13 UTC, ARADDCC012 requested changes

2024-01-26 14:13 UTC, ARADDCC012 commented on frontend/src/common/PageWithTabs.tsx
> +              style={{ pointerEvents: 'auto' }}
Can we use `sx` here?

2024-02-05 16:08 UTC, ARADDCC012 requested changes

2024-02-05 16:08 UTC, ARADDCC012 commented on frontend/src/common/PageWithTabs.tsx
> +              sx={{ pointerEvents: 'auto' }}
Is this needed? I believe the default behaviour of `Tab` should handle this for us.

2024-02-05 16:30 UTC, ARADDCC002 commented on frontend/src/model/beta/ModelImages.tsx
> -              disabled={!model.card}
Nah we discussed this and we reckon that Images can be added before a schema is set

2024-02-05 16:47 UTC, ARADDCC012 commented on frontend/src/common/PageWithTabs.tsx
> +  disabledText?: string
I don't think this is being used is it?

2024-02-05 17:06 UTC, ARADDCC012 approved these changes

2024-02-06 09:22 UTC, merged