Bugfix/empty query params and broken filters
gchq/Bailo pull request #1044
Opened 2024-01-31 17:13 UTC by JR40159

2024-02-01 23:57 UTC, a3957273 approved these changes

2024-02-02 10:35 UTC, ARADDCC012 requested changes

2024-02-02 10:35 UTC, ARADDCC012 commented on frontend/src/common/ChipSelector.tsx
> +      tags: (string | '')[]
This can be `string[]`

2024-02-02 10:35 UTC, ARADDCC012 commented on frontend/src/common/ChipSelector.tsx
> +      selectedTags: string | ''
This can just be `string`

2024-02-02 10:35 UTC, ARADDCC012 commented on frontend/src/common/ChipSelector.tsx
> +      onChange: (value: string | '') => void
Can just be `string`

2024-02-02 11:51 UTC, ARADDCC012 approved these changes

2024-02-02 12:55 UTC, merged