Feature/bai 227 confirmation dialogue
gchq/Bailo pull request #114
Opened 2022-08-23 14:51 UTC by ARADDCC011

Added ConfirmationDialogue.tsx, and implemented it to confirm model deletion in [uuid].tsx, calling a dummy delete function

2022-08-23 14:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gchq/Bailo?pullRequest=114) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gchq/Bailo?pullRequest=114) before we can accept your contribution.<br/><hr/>**ARADDCC011** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gchq/Bailo?pullRequest=114) it.</sub>

2022-08-23 14:53 UTC, ARADDCC002 commented on pages/model/[uuid].tsx
> +    console.log("Model would be deleted if this function did anything")
Remove log

2022-08-23 14:55 UTC, a3957273 requested changes

2022-08-23 14:55 UTC, a3957273 commented on src/common/ConfirmationDialogue.tsx
> +import EmptyBlob from './EmptyBlob'
Lots of these imports aren't needed.

2022-08-24 08:04 UTC, ARADDCC002 commented
I think it would be worth adding a test for this component too.

2022-08-30 09:14 UTC, ARADDCC002 approved these changes

2022-09-15 09:21 UTC, closed without merging

2022-09-15 09:22 UTC, ARADDCC002 commented
Closed as the work is being continued in #141