Feature/bai 849 use open telemetry to send instrumentation info
gchq/Bailo pull request #1158
Opened 2024-03-08 08:25 UTC by JR40159

2024-03-08 12:03 UTC, a3957273 requested changes

2024-03-08 12:03 UTC, a3957273 commented on backend/config/default.cjs
> +    serviceName: 'backend',
This should probably include `authenticationToken`.  The config should include every possible field, even if it defaults to empty.

2024-03-08 14:19 UTC, JR40159 commented
Add the ability to turn on OT debug model via config

2024-03-11 13:13 UTC, ARADDCC013 approved these changes

2024-03-12 10:10 UTC, merged