Improve personal access token dialog
gchq/Bailo pull request #1163
Opened 2024-03-13 16:28 UTC by ARADDCC012

2024-03-18 17:02 UTC, ARADDCC002 requested changes

2024-03-19 11:20 UTC, JR40159 commented
The warning 'You will never be able to access this token again. Make sure to copy it to a safe place.' should probably persist across all the tabs

2024-04-03 23:06 UTC, a3957273 requested changes
internal notes

2024-04-08 17:55 UTC, a3957273 approved these changes

2024-04-09 09:04 UTC, merged