BAI-1286 TokenAgent Improvements
gchq/Bailo pull request #1281
Opened 2024-05-22 12:01 UTC by bw27492

- Now reads env variables or cli input

2024-05-22 14:18 UTC, GB27247 requested changes

2024-05-22 14:22 UTC, GB27247 commented on lib/python/src/bailo/core/agent.py
> +                secret_key = getpass.getpass("BAILO SECRET KEY ")
Just be aware this input will not work for some environments. Such as emulators or pseudo-terminals.

2024-05-23 09:35 UTC, bw27492 commented on lib/python/src/bailo/core/agent.py
> +            except:
Done

2024-05-23 09:35 UTC, bw27492 commented on lib/python/src/bailo/core/agent.py
> +                secret_key = getpass.getpass("BAILO SECRET KEY ")
Done

2024-05-23 09:35 UTC, bw27492 commented on lib/python/src/bailo/core/agent.py
> +                secret_key = getpass.getpass("BAILO SECRET KEY ")
Done

2024-05-23 14:22 UTC, bw27492 commented on lib/python/src/bailo/core/agent.py
>          self.secret_key = secret_key
Now checks when instantiating a client object (generally for all auth methods)

2024-05-23 14:50 UTC, bw27492 commented on lib/python/src/bailo/core/agent.py
No longer needed as all endpoints can take tokens

2024-05-23 16:23 UTC, GB27247 approved these changes

2024-05-23 16:23 UTC, merged