Add initial export capability
gchq/Bailo pull request #1334
Opened 2024-06-19 06:24 UTC by a3957273

2024-07-01 15:27 UTC, JR40159 requested changes

2024-07-01 15:27 UTC, JR40159 commented on backend/src/services/export.ts
Could we update the name of this new service since we have different types of exports now?

2024-07-01 15:27 UTC, JR40159 commented on backend/src/services/export.ts
No tests :(

2024-07-01 15:27 UTC, JR40159 commented on backend/src/routes/v2/model/modelcard/getModelCardHtml.ts
No tests :(

2024-07-10 11:33 UTC, JR40159 approved these changes

2024-07-30 13:19 UTC, ARADDCC002 approved these changes

2024-07-30 14:20 UTC, merged