Bai 1348/mirrored model creation
gchq/Bailo pull request #1348
Opened 2024-06-27 15:53 UTC by GB27247

2024-07-01 16:07 UTC, ARADDCC012 requested changes

2024-07-01 16:07 UTC, ARADDCC012 commented on frontend/src/entry/model/releases/EditableRelease.tsx
> +      {(!model.settings.mirror || model.settings.mirror?.sourceModelId) && (
We'll still want the heading so the release name is shown. Are you doing this to hide the edit/delete buttons? If so, we should instead conditionally render those buttons. You'll just need to pass through a `readOnly` prop and handle it within `EditableFormHeading`.

2024-07-01 16:07 UTC, ARADDCC012 commented on frontend/src/entry/overview/FormEditPage.tsx
> +                hidden={readOnly}
Again, we should be conditionally rendering this button.

However, due to your conditional logic in `frontend/src/entry/overview/Overview.tsx` I don't think we need to do hide anything in this component.

2024-07-01 16:07 UTC, ARADDCC012 commented on frontend/src/entry/overview/Overview.tsx
> +      {page === OverviewPage.FORM && <FormEditPage entry={entry} readOnly />}
Why are you passing `readOnly` into `FormEditPage`? Based on your logic `FormEditPage` will not be rendered in read-only mode, so the `readOnly` prop will always be `false`.

2024-07-01 16:07 UTC, ARADDCC012 commented on frontend/src/entry/overview/FormEditPage.tsx
> +  readOnly?: boolean
This prop looks unnecessary to me due to your conditional logic in `frontend/src/entry/overview/Overview.tsx`

2024-07-01 16:07 UTC, ARADDCC012 commented on frontend/src/marketplace/EntryList.tsx
> +          {entry.readonly && <Typography>readonly</Typography>}
This is user-facing so consider doing:
```
{entry.readonly && <Typography> (read-only)</Typography>}
```

2024-07-01 16:34 UTC, JR40159 requested changes

2024-07-01 16:34 UTC, JR40159 commented on frontend/src/common/PageWithTabs.tsx
> +              [READONLY] Mirrored from {sourceModelId}
I like making it clear where the model comes from but I'm not a big fan of using a banner for this, it's in danger of being over-used. Could we include this information next to the model name at the top or something?

2024-07-01 16:34 UTC, JR40159 commented on frontend/pages/entry/new.tsx
Now we have three options, I'm noticing that the page doesn't copy well with being resized

2024-07-01 16:34 UTC, JR40159 commented on frontend/src/entry/overview/Overview.tsx
> +      message='This mirrored model has no model card. Please export the model card from the source model.'
If I manually a model card data into the DB then I still see this message rather than the model card?

2024-07-01 16:34 UTC, JR40159 commented on frontend/pages/model/[modelId].tsx
>                disabledText: 'Select a schema to view this tab',
This still appears for mirrored models but isn't applicable since a user cannot select a schema

2024-07-03 09:00 UTC, GB27247 commented on frontend/pages/entry/new.tsx
I've modified the styling so the cards wrap around when the page is too small.

2024-07-03 15:34 UTC, ARADDCC012 approved these changes

2024-07-10 10:43 UTC, JR40159 requested changes
On the create entry page for a mirrored model, can you make the source model ID mandatory?

2024-07-10 12:55 UTC, JR40159 approved these changes

2024-07-10 16:32 UTC, ARADDCC012 requested changes

2024-07-10 16:32 UTC, ARADDCC012 commented on frontend/src/entry/CreateEntry.tsx
> +                    disabled={!isFormValid || (!sourceModelId && createEntryKind === CreateEntryKind.MIRRORED_MODEL)}
This additional logic should be added to `isFormValid` instead of here.

2024-07-10 16:46 UTC, ARADDCC012 commented on frontend/src/entry/overview/Overview.tsx
> +      {page === OverviewPage.FORM && <FormEditPage entry={entry} currentUserRoles={currentUserRoles} readOnly />}
Whoops, just noticed this one. Passing `readOnly` without a specified value in react is the same as doing `readOnly={true}` so you'll need to update this to the following:
```
{page === OverviewPage.FORM && <FormEditPage entry={entry} currentUserRoles={currentUserRoles} readOnly={readOnly} />}
```

2024-07-12 10:09 UTC, ARADDCC012 approved these changes

2024-07-15 11:16 UTC, merged