Fix image upload authorisation
gchq/Bailo pull request #1395
Opened 2024-07-09 10:50 UTC by GB27247

2024-07-09 12:07 UTC, a3957273 approved these changes

2024-07-09 12:08 UTC, a3957273 requested changes
Please add a unit test to ensure this bug doesn't occur in the future.

2024-07-10 10:24 UTC, JR40159 requested changes

2024-07-10 10:24 UTC, JR40159 commented on backend/test/connectors/authorisation/base.spec.ts
> +  test('image > push with no roles', async () => {
Could you also add a test for the equivalent push condition please?

2024-07-10 12:53 UTC, JR40159 approved these changes

2024-07-10 13:31 UTC, merged