Bai 721 bailo GitHub pages docs no longer have a working logo
gchq/Bailo pull request #1417
Opened 2024-07-25 08:35 UTC by IR96334

2024-07-26 06:55 UTC, ARADDCC002 approved these changes

2024-07-26 06:55 UTC, ARADDCC002 commented on lib/landing/src/Wrapper.tsx
>              <Button href='https://github.com/gchq/bailo' sx={{ color: 'white' }}>
If we're making the change to the documentation button we should replicate it here too and wrap this button in `<Link />`

2024-07-26 06:56 UTC, ARADDCC002 requested changes
Accidentally approved instead of requested changes!

2024-07-29 13:04 UTC, ARADDCC012 approved these changes

2024-07-31 09:50 UTC, ARADDCC002 approved these changes

2024-07-31 09:50 UTC, merged