Feature/bai 1343 add announcement banner
gchq/Bailo pull request #1424
Opened 2024-07-31 16:27 UTC by ARADDCC002

2024-08-06 12:05 UTC, GB27247 requested changes

2024-08-07 12:27 UTC, ARADDCC002 commented on frontend/src/Annoucement.tsx
> +  }
This is a mistake and should be memozied, updated!

2024-08-07 12:55 UTC, ARADDCC002 commented on frontend/src/Wrapper.tsx
> +                <Announcement message={uiConfig.announcement.text} onClose={handleAnnouncementOnClose} />
We discussed this and chose to go at the bottom to keep it consistent with other applications with similar messages. If enough users prefer it moved we can look to doing that.

2024-08-07 14:03 UTC, GB27247 submitted a review, later dismissed

2024-08-07 16:37 UTC, ARADDCC012 requested changes

2024-08-07 16:37 UTC, ARADDCC012 commented on frontend/src/Banner.tsx
> +      <Stack>
This stack isn't needed as it only has one child

2024-08-07 16:37 UTC, ARADDCC012 commented on frontend/src/Wrapper.tsx
> +const DISMISSED_COOKIE_NAME = 'dismissed-timestamp'
Can we move this into `frontend/utils/constants.ts`?

2024-08-07 16:37 UTC, ARADDCC012 commented on frontend/src/Wrapper.tsx
> +        uiConfig &&
We've already checked `uiConfig` is truthy above so this check isn't needed

2024-08-07 16:37 UTC, ARADDCC012 commented on frontend/src/Wrapper.tsx
> +import Cookies from 'js-cookie'
I know the library uses `Cookies` in their examples, but can we use `cookies` as it then follows our naming conventions?

2024-08-07 16:37 UTC, ARADDCC012 commented on frontend/src/Announcement.tsx
> +    <>
This fragment isn't needed

2024-08-07 16:37 UTC, ARADDCC012 commented on frontend/src/Announcement.tsx
> +          ml: 'auto',
Could combine `ml` and `mr` by using `mx: 'auto'`

2024-08-07 16:37 UTC, ARADDCC012 commented on frontend/src/Announcement.tsx
> +          {!showFullText ? `${message.slice(0, 100)}...` : message}
Can we reverse the logic here? It's a little confusing to have a ternary written this way round. Consider:
```
{showFullText ? message : `${message.slice(0, 100)}...`}
```

2024-08-07 16:37 UTC, ARADDCC012 commented on frontend/src/Wrapper.tsx
> +            <Box sx={{ mb: 2 }}>
Is this box necessary? I don't think we want the banner to take up any space from the existing content, we want it to sit on top of it.

Also consider combining the two conditional blocks into:
```
{uiConfig && annoucementBannerOpen && ( ... )}
```

2024-08-08 17:58 UTC, ARADDCC012 approved these changes

2024-08-09 10:41 UTC, merged