Add model card actions
gchq/Bailo pull request #1468
Opened 2024-08-21 15:14 UTC by GB27247

2024-08-28 15:41 UTC, JR40159 requested changes

2024-08-28 15:41 UTC, JR40159 commented on backend/src/connectors/authorisation/base.ts
> +          ([ModelAction.Write, ModelAction.Update].some((a) => a === action) &&
For clarity I would probably split this into two if statements/conditions:
1. For `ModelAction.Write` that tells the user they don't have permission to update the model card if they don't have one of 'owner', 'mtr', 'msro', 'contributor'.
2. For `ModelAction.Update`  that tells the user they don't have permission to update the model if they don't have one of 'owner', 'mtr', 'msro'.

2024-09-02 14:42 UTC, ARADDCC012 approved these changes

2024-09-02 15:06 UTC, JR40159 approved these changes

2024-09-02 15:16 UTC, merged