Feature/bai 1461 manual rerequest filescanning
gchq/Bailo pull request #1633
Opened 2024-11-27 17:17 UTC by ARADDCC002

2024-12-03 14:25 UTC, PE39806 commented
The "Last ran at..." text does not appear when viruses are found, and it would be helpful to see the time for when a scan was last run to check whether re-running a scan has completed or not.
![image](https://github.com/user-attachments/assets/55589299-e327-4b34-87ad-54303244b52f)

2024-12-04 09:35 UTC, JR40159 requested changes

2024-12-04 09:37 UTC, JR40159 submitted a review, later dismissed
As mentioned in the ticket, this might require a migration as files that existing prior to adding the ability to scan them might be missing the `avScan` property. Could you check this please?

2024-12-04 13:36 UTC, ARADDCC002 commented
> As mentioned in the ticket, this might require a migration as files that existing prior to adding the ability to scan them might be missing the `avScan` property. Could you check this please?

Does migration 009 not cover this use case?

2024-12-05 10:16 UTC, PE39806 commented
Test what happens when a scanner is killed off part way through a scan - we want to be able to catch this and update the scan result to "could not complete" rather than indefinitely reporting "virus scan in progress".

2024-12-09 16:23 UTC, PE39806 commented on backend/src/connectors/fileScanning/clamAv.ts
> +const maxInitRetries = 5
I'd like the max retry count `maxInitRetries = 5` and delay between pings `10000` to be configurable like `retryDelayInMinutes` e.g. `connectors.fileScanners.maxInitRetries` and `connectors.fileScanners.initRetryDelay`.

2024-12-09 16:23 UTC, PE39806 commented on backend/test/clients/modelScan.spec.ts
> +  test('scanFile > rejected', async () => {
Revert `scanFile` to `scanStream`

2024-12-10 08:32 UTC, PE39806 approved these changes

2024-12-10 09:57 UTC, merged