Feature/bai 75 containerize app
gchq/Bailo pull request #23
Opened 2022-02-08 13:56 UTC by at55425

Run the app in its own container instead of relying on host Docker.

Uses img for builds.

Uses docker for registry login (img doesn't send complete authorisation headers), but "docker login" doesn't require the docker daemon to be running. It populates .docker/config.json that img then uses for pushing the built image into the registry.

2022-02-18 11:08 UTC, a3957273 requested changes

2022-02-25 10:16 UTC, at55425 commented on server/routes/v1/upload.ts
> +      .timeout(60000*8)
Recent tests are 6 m for first build (before seldon image was pulled by the app) and then 4.3s for another build (admittedly with the same underlying model binary and code)

2022-02-25 10:54 UTC, at55425 commented on server/routes/v1/upload.ts
> +      .timeout(60000*8)
Having the image pulled by the app took 4m30s (1 run), resulting in first initial model image build->push to registry time of 2m 55.5s.

2022-02-25 10:57 UTC, at55425 commented on server/routes/v1/upload.ts
> +      .timeout(60000*8)
(subsequent build of *same model* via separate model upload was 4.4s)

2022-03-01 11:45 UTC, a3957273 approved these changes

2022-03-05 16:17 UTC, a3957273 requested changes
Unsure about this given `seccomp:unconfined`

2022-03-10 15:37 UTC, a3957273 requested changes

2022-03-10 15:37 UTC, a3957273 commented on .github/workflows/node.js.yml
>        - run: npm run lint
You no longer need to run `npm run build` here, as it's built inside of docker-compose.

2022-03-10 15:37 UTC, a3957273 commented on .github/workflows/node.js.yml
>        - run: npm ci
You no longer need to install dependencies here, as they're installed inside the container.

2022-03-10 16:23 UTC, ARADDCC002 approved these changes

2022-03-10 16:23 UTC, a3957273 approved these changes

2022-03-10 16:25 UTC, at55425 commented
Run app in container

2022-03-10 16:25 UTC, merged