added link to explain error
gchq/Bailo pull request #487
Opened 2023-05-12 08:06 UTC by TT38665

A link was added alongside the error, that leads to more information about why it occurred.

2023-05-19 00:26 UTC, a3957273 requested changes

2023-05-19 00:26 UTC, a3957273 commented on frontend/pages/docs/users/upload-a-model/updating-a-model.mdx
> +### Duplicate Version
This should be it's own unique page, so that we can link directly to it.

2023-05-19 00:26 UTC, a3957273 commented on frontend/pages/docs/users/upload-a-model/updating-a-model.mdx
> +The model that you have tried to update, already has the same model version.
Nitpick: comma isn't necessary here.

2023-05-19 00:26 UTC, a3957273 commented on frontend/pages/model/[uuid]/new-version.tsx
> +        href='/docs/users/upload-a-model/updating-a-model'
The URL should not be hardcoded, as there may be different errors.  It should instead parse the URL from the error repsonse.

2023-05-19 00:26 UTC, a3957273 commented on frontend/src/MessageAlert.tsx
> +export default function MessageAlert({ message, severity, linkText, href }: MessageAlertProps) {
This is a nice function.

2023-05-30 15:13 UTC, TT38665 commented on frontend/pages/docs/users/upload-a-model/updating-a-model.mdx
> +The model that you have tried to update, already has the same model version.
Sorted

2023-05-30 15:15 UTC, TT38665 commented on frontend/src/MessageAlert.tsx
> +export default function MessageAlert({ message, severity, linkText, href }: MessageAlertProps) {
Thank you

2023-06-04 15:19 UTC, a3957273 approved these changes

2023-07-06 14:15 UTC, merged