added a review page with an approval list
gchq/Bailo pull request #673
Opened 2023-08-14 16:07 UTC by ARADDCC002

2023-08-15 10:06 UTC, JR40159 commented on backend/src/models/v2/Approval.ts
> +const ApprovalRequestModel = model<ApprovalRequestInterface>('v2_Release', ApprovalRequestSchema)
V2_Approval?

2023-08-15 19:01 UTC, a3957273 requested changes

2023-08-15 19:01 UTC, a3957273 commented on frontend/types/types.ts
> +  entities: Array<string>
No entities here anymore.

2023-08-16 15:51 UTC, ARADDCC002 commented on backend/src/routes/v2/approval/getApprovals.ts
> +    const active = req.query.isActive === 'true'
This is being handled in another ticket

2023-08-16 15:51 UTC, ARADDCC002 commented on backend/src/routes/v2/approval/getApprovals.ts
> +    if (isActive !== 'true' && isActive !== 'false') {
This is being handled in another ticket

2023-08-16 15:51 UTC, ARADDCC002 commented on backend/src/routes/v2/approval/getApprovals.ts
> +    isActive: z.string({
This is being handled in another ticket

2023-08-17 16:08 UTC, a3957273 approved these changes

2023-08-18 08:18 UTC, merged