Add post review response and move review count to be a response header
gchq/Bailo pull request #749
Opened 2023-09-19 17:57 UTC by JR40159

2023-09-21 13:07 UTC, a3957273 requested changes

2023-09-21 13:07 UTC, a3957273 commented on backend/src/services/v2/review.ts
> + */
Could you add that this requires the `model` attribute?

2023-09-21 13:24 UTC, JR40159 commented on backend/src/routes/v2/review/getReviews.ts
> +    res.setHeader('x-count', reviews.length)
http headers are case-insensitive?

2023-09-21 14:05 UTC, JR40159 commented on backend/src/routes.ts
> +  server.post('/api/v2/reviews/:modelId/:semver/:role', ...postReviewResponse)
See previous comment and I would also add that these pieces of data are used to identify the specific resource so, for me, should be part of the URI. The body should contain the data that the user is wanting to write, not an identifier of that data

2023-09-21 15:17 UTC, ARADDCC002 commented on backend/src/routes/v2/review/getReviews.ts
> +    res.setHeader('x-count', reviews.length)
They're not case-sensitive, but I can see us keeping it upper-case to be consistent in other areas of the code but overall I don't think it's a massive issue if it's kept as-is.

2023-09-21 16:36 UTC, JR40159 commented on backend/src/routes/v2/review/getReviews.ts
> +    res.setHeader('x-count', reviews.length)
I also noticed that when unit testing, the header name gets lowercased anyway regardless of what case is used here

2023-09-25 13:11 UTC, a3957273 approved these changes

2023-09-25 13:48 UTC, merged