added a submission page for edit, new version and deployment forms
gchq/Bailo pull request #84
Opened 2022-05-09 11:01 UTC by ARADDCC002

2022-05-12 12:09 UTC, a3957273 requested changes

2022-05-12 12:10 UTC, a3957273 commented on pages/model/[uuid]/deploy.tsx
> +import DeploymentSubmission from '@/src/Form/DeploymentSubmission'
Doesn't follow import of other imports, ../../../

2022-05-12 15:13 UTC, ARADDCC002 commented on pages/model/[uuid]/deploy.tsx
> +    <>
Resolved

2022-05-12 15:14 UTC, ARADDCC002 commented on pages/model/[uuid]/new-version.tsx
> +import ModelExportAndSubmission from '@/src/Form/ModelExportAndSubmission'
Think this was auto import! Resolved

2022-05-12 15:21 UTC, ARADDCC002 commented on pages/model/[uuid]/edit/[version].tsx
> +import ModelEditSubmission from '@/src/Form/ModelEditSubmission'
Resolved

2022-05-16 15:26 UTC, a3957273 requested changes

2022-05-16 15:26 UTC, a3957273 commented on pages/model/[uuid]/new-version.tsx
> +        isComplete: () => true,
Similar `isComplete` consideration.

2022-05-17 22:40 UTC, a3957273 approved these changes

2022-05-17 22:41 UTC, merged