Feature/bai 168 as a developer i want to update our old code to have unit tests
gchq/Bailo pull request #89
Opened 2022-06-01 15:24 UTC by ARADDCC002

2022-06-15 15:17 UTC, a3957273 requested changes

2022-06-15 16:15 UTC, ARADDCC002 commented on server/routes/v1/deployment.spec.ts
> +const deploymentSchema: any = {
I do like this idea, will make it easier for organisation. Do we want this in this ticket or another one? Happy to include it in this if it isn't too much of a change.
Conscious that the other comment you made about the address parameters is a bit a big change (and by big I mean lots of copy/pasting), so wondering if they deserve their own PR or not.

2022-06-16 08:48 UTC, ARADDCC002 commented on .github/workflows/node.js.yml
> +      - run: sudo chown -R runner:docker certs
Done

2022-06-16 09:02 UTC, ARADDCC002 commented on server/index.ts
> +server.use(expressErrorHandler)
Not sure! Seems to be working without it, so I think it can be removed.

2022-06-16 15:55 UTC, ARADDCC002 commented on server/routes/v1/deployment.spec.ts
> +    expect(res.statusCode).toBe(200)
Done

2022-06-16 15:55 UTC, ARADDCC002 commented on server/routes/v1/deployment.spec.ts
> +const deploymentSchema: any = {
Done

2022-06-20 21:44 UTC, a3957273 approved these changes

2022-06-21 09:04 UTC, merged