implemented error message
gchq/Bailo pull request #890
Opened 2023-11-17 16:35 UTC by TT38665

2023-11-18 17:59 UTC, a3957273 requested changes

2023-11-18 17:59 UTC, a3957273 commented on frontend/src/model/beta/overview/TemplatePage.tsx
> +  const { schemas, isSchemasLoading, isSchemasError } = useGetSchemas(model.card.schemaId)
You're grabbing the `schemas` for this page, but then don't seem to be using them anywhere?

2023-11-21 21:29 UTC, a3957273 requested changes

2023-11-21 21:29 UTC, a3957273 commented on frontend/pages/beta/model/[modelId]/access-request/schema.tsx
>    if (isSchemasError) {
You check to see whether there is a `isSchemasError` here.  Why are you checking for it again three lines up?

2023-11-28 17:22 UTC, ARADDCC012 commented on frontend/pages/beta/model/[modelId]/access-request/schema.tsx
> +  const error = MultipleErrorWrapper(`Unable to fetch schemas`, {
We have a generic message format of "Unable to load X page". So for here it would be "Unable to load schema page"

2023-11-28 17:23 UTC, ARADDCC012 requested changes

2023-11-28 17:23 UTC, ARADDCC012 commented on frontend/pages/beta/model/[modelId]/access-request/schema.tsx
> +  const error = MultipleErrorWrapper(`Unable to fetch schemas`, {
We have a generic message format of "Unable to load X page". So for here it would be "Unable to load schema page"

2023-12-01 10:48 UTC, ARADDCC012 approved these changes

2023-12-01 18:35 UTC, a3957273 approved these changes

2023-12-01 18:35 UTC, merged