added required asterix to v2 form questions
gchq/Bailo pull request #988
Opened 2024-01-03 15:08 UTC by ARADDCC002

2024-01-03 16:37 UTC, a3957273 requested changes

2024-01-03 16:37 UTC, a3957273 commented on frontend/src/MuiForms/Dropdown.tsx
> +        {required && <span style={{ color: 'red' }}>{' *'}</span>}
Instead of hard coding red we should probably use something like 'palette.error.light'

2024-01-05 13:33 UTC, a3957273 approved these changes

2024-01-09 12:34 UTC, ARADDCC012 requested changes

2024-01-09 12:34 UTC, ARADDCC012 commented on frontend/src/MuiForms/CustomTextInput.tsx
> +        {required && <span style={{ color: theme.palette.error.light }}>{' *'}</span>}
We use `theme.palette.error.main` for all other required asterisks. I'd vote for using the same for all of the ones in this PR too

2024-01-09 12:39 UTC, ARADDCC012 approved these changes

2024-01-09 15:09 UTC, merged