Feature/bai 178 integrate dark mode
gchq/Bailo pull request #99
Opened 2022-07-27 17:24 UTC by ARADDCC002

2022-08-08 12:36 UTC, a3957273 commented
<img width="225" alt="Screenshot 2022-08-08 at 13 33 40" src="https://user-images.githubusercontent.com/89583054/183418898-8245bdbf-382b-42cd-a7c9-230146571c4b.png">

<img width="238" alt="Screenshot 2022-08-08 at 13 34 12" src="https://user-images.githubusercontent.com/89583054/183419036-741a0cbf-6907-41e3-bd1b-59979e637bd9.png">

<img width="483" alt="Screenshot 2022-08-08 at 13 34 17" src="https://user-images.githubusercontent.com/89583054/183419042-422d996b-c4ce-4bf5-8339-152cad25da22.png">

Hovering over buttons breaks things.

2022-08-08 13:04 UTC, a3957273 requested changes

2022-08-09 08:01 UTC, ARADDCC002 commented on pages/deployment/[uuid].tsx
> +          <b>{line}</b>
Added a background to the text so it stands out, and a border radius so it somewhat resembles a button.

2022-08-09 08:08 UTC, ARADDCC002 commented on pages/model/[uuid].tsx
>  import DownArrow from '@mui/icons-material/KeyboardArrowDown'
Fixed

2022-08-09 08:10 UTC, ARADDCC002 commented on pages/review.tsx
>                      <Link href={`/model/${requestObj.deployment?.model?.uuid}`} passHref>
As said in another comment I can't see us implementing our own Link component anywhere. Happy to do it all in this ticket but might be worth putting in its own one?

2022-08-09 11:56 UTC, ARADDCC002 commented on pages/index.tsx
> +                      sx={{ backgroundColor: '#f5f5f5', color: '#000000de' }}
Think I've changed back all the ones except the model overview (just due to the background colour and outlined variant of the chip)

2022-08-09 14:19 UTC, ARADDCC002 commented
> <img alt="Screenshot 2022-08-08 at 13 33 40" width="225" src="https://user-images.githubusercontent.com/89583054/183418898-8245bdbf-382b-42cd-a7c9-230146571c4b.png">
> 
> <img alt="Screenshot 2022-08-08 at 13 34 12" width="238" src="https://user-images.githubusercontent.com/89583054/183419036-741a0cbf-6907-41e3-bd1b-59979e637bd9.png">
> 
> <img alt="Screenshot 2022-08-08 at 13 34 17" width="483" src="https://user-images.githubusercontent.com/89583054/183419042-422d996b-c4ce-4bf5-8339-152cad25da22.png">
> 
> Hovering over buttons breaks things.

This should now be fixed. I don't know why but the white hover colour wasn't appearing for me..... but got someone else testing my new fix.

2022-08-09 15:27 UTC, a3957273 approved these changes

2022-08-09 15:36 UTC, merged