Added get_download_file_token method to client
gchq/Bailo pull request #997
Opened 2024-01-05 11:35 UTC by bw27492

2024-01-11 13:28 UTC, GB27247 requested changes

2024-01-11 13:28 UTC, GB27247 commented on lib/python-beta/src/bailo/core/client.py
> +        if isinstance(self.agent, TokenAgent):
`isinstance` is a built in function that considers inheritance eg `isinstance(Agent(), TokenAgent)` will be `True`. Instead you want something like `type(self.agent) == TokenAgent`

2024-01-11 13:28 UTC, GB27247 commented on lib/python-beta/src/bailo/core/client.py
> +            raise Exception("get_download_file_token requires the use of TokenAgent")
Does this need to be a separate method? I'd consider adding this to `get_download_file` and switching the endpoint given the Agent instance

2024-01-12 11:24 UTC, a3957273 approved these changes

2024-01-12 12:03 UTC, merged